/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.locutor;

import controller.locutor.MusicaController;
import controller.locutor.PlayListaController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.ObjetoListaMusica;
import objetos.ObjetoMusica;

/**
 *
 * @author leonardo
 */
public class TelaListaMusica extends javax.swing.JInternalFrame {

    private List<ObjetoListaMusica> objListaM;
    private List<ObjetoMusica> objMusica;

    /**
     * Creates new form TelaEvento1
     */
    public TelaListaMusica() {
        initComponents();
        readTableLista();
        readTableMusica();
    }

    public void readTableLista() {
        PlayListaController listaC = new PlayListaController();
        this.objListaM = listaC.listasPlayListas();
        this.tableLista();
    }

    public void searchTableLista(String search) {
        PlayListaController listaC = new PlayListaController();
        this.objListaM = listaC.consultarPlayLista(search);
        this.tableLista();
    }

    public void tableLista() {
        DefaultTableModel modelo = (DefaultTableModel) jTListaM.getModel();
        modelo.setNumRows(0); // Limpando a tabela

        for (ObjetoListaMusica lm : this.objListaM) {

            modelo.addRow(new Object[]{
                lm.getIdLista(),
                lm.getNome()
            });

        }
    }

    public void readTableMusica() {
        MusicaController musicaC = new MusicaController();
        this.objMusica = musicaC.listarListasMusicas();
        this.tableMusica();
    }

    public void searchTableMusica(String search) {
        MusicaController musicaC = new MusicaController();
        this.objMusica = musicaC.consultarMusicas(search);
        this.tableMusica();
    }

    public void tableMusica() {
        DefaultTableModel modelo = (DefaultTableModel) jTMusicas.getModel();
        modelo.setNumRows(0); // Limpando a tabela

        for (ObjetoMusica m : this.objMusica) {

            modelo.addRow(new Object[]{
                m.getIdMusica(),
                m.getNome(),
                m.getNomeCantor(),
                m.getBanda(),
                m.getEstiloMusical()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTListaM = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        searchPlayLista = new javax.swing.JTextField();
        buttonBucarPlayLista = new javax.swing.JButton();
        buttonCriarPlayLista = new javax.swing.JButton();
        buttonExcluirPlayLista = new javax.swing.JButton();
        buttonAlterarPlayLista = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeLista = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMusicas = new javax.swing.JTable();
        buttonBuscarMusica = new javax.swing.JButton();
        searchMusica = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buttonAddMusicaPlayLista = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jTextField3.setText("jTextField3");

        setClosable(true);
        setIconifiable(true);
        setTitle("Play Listas");
        setToolTipText("");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Play Listas"));

        jTListaM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTListaM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTListaMMouseClicked(evt);
            }
        });
        jTListaM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTListaMKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTListaM);

        jLabel4.setText("Pesquisar Lista");

        searchPlayLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPlayListaActionPerformed(evt);
            }
        });

        buttonBucarPlayLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        buttonBucarPlayLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBucarPlayListaActionPerformed(evt);
            }
        });

        buttonCriarPlayLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        buttonCriarPlayLista.setText("Criar Lista");
        buttonCriarPlayLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCriarPlayListaActionPerformed(evt);
            }
        });

        buttonExcluirPlayLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil_delete.png"))); // NOI18N
        buttonExcluirPlayLista.setText("Excluir Lista");
        buttonExcluirPlayLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirPlayListaActionPerformed(evt);
            }
        });

        buttonAlterarPlayLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        buttonAlterarPlayLista.setText("Alterar Lista");
        buttonAlterarPlayLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarPlayListaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar"));

        jInternalFrame1.setClosable(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setText("Nome da  Lista:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nomeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 0, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(buttonCriarPlayLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonAlterarPlayLista)
                        .addGap(44, 44, 44)
                        .addComponent(buttonExcluirPlayLista))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)
                        .addComponent(searchPlayLista, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonBucarPlayLista)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCriarPlayLista)
                    .addComponent(buttonAlterarPlayLista)
                    .addComponent(buttonExcluirPlayLista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchPlayLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(buttonBucarPlayLista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Músicas"));

        jInternalFrame2.setClosable(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Cantor", "Banda", "Estilo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTMusicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMusicasMouseClicked(evt);
            }
        });
        jTMusicas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTMusicasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTMusicas);

        buttonBuscarMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        buttonBuscarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarMusicaActionPerformed(evt);
            }
        });

        searchMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMusicaActionPerformed(evt);
            }
        });

        jLabel5.setText("Pesquisar Música");

        buttonAddMusicaPlayLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        buttonAddMusicaPlayLista.setText("Adicionar Música a Lista");
        buttonAddMusicaPlayLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddMusicaPlayListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBuscarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(buttonAddMusicaPlayLista)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(buttonAddMusicaPlayLista)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(buttonBuscarMusica))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.getAccessibleContext().setAccessibleName("Play Listas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(250, 20, 1029, 543);
    }// </editor-fold>//GEN-END:initComponents

    private void jTListaMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTListaMKeyPressed
        ObjetoListaMusica listaM = this.objListaM.get(jTListaM.getSelectedRow());
        nomeLista.setText(listaM.getNome());
    }//GEN-LAST:event_jTListaMKeyPressed

    private void jTListaMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTListaMMouseClicked
        ObjetoListaMusica listaM = this.objListaM.get(jTListaM.getSelectedRow());
        nomeLista.setText(listaM.getNome());

    }//GEN-LAST:event_jTListaMMouseClicked

    private void buttonExcluirPlayListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirPlayListaActionPerformed
        if (jTListaM.getSelectedRow() != -1) {

            int check = JOptionPane.showConfirmDialog(null, "Confirma a exclusão", "Excluir", JOptionPane.YES_NO_OPTION);

            if (check == 0) {
                ObjetoListaMusica dadoslista = this.objListaM.get(jTListaM.getSelectedRow());

                PlayListaController listaC = new PlayListaController();
                listaC.setLista_id(dadoslista.getIdLista());
                listaC.excluirPlayLista();
                nomeLista.setText(""); // Limpar input
                readTableLista();
            }

        } else {
            this.messageJOptionPane("Selecione uma lista para excluir");
        }
    }//GEN-LAST:event_buttonExcluirPlayListaActionPerformed

    private void buttonBucarPlayListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBucarPlayListaActionPerformed
        this.searchTableLista(searchPlayLista.getText());
    }//GEN-LAST:event_buttonBucarPlayListaActionPerformed

    private void searchPlayListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPlayListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPlayListaActionPerformed

    private void buttonAlterarPlayListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarPlayListaActionPerformed

        if (jTListaM.getSelectedRow() != -1) {
            ObjetoListaMusica dadoslista = this.objListaM.get(jTListaM.getSelectedRow());
            
            PlayListaController listaC = new PlayListaController();

            listaC.setLista_id(dadoslista.getIdLista());
            listaC.setNome(nomeLista.getText());
            listaC.validInput();

            if (listaC.isValid()) {                

                if (!nomeLista.getText().equals(dadoslista.getNome())) {
                    int check = JOptionPane.showConfirmDialog(null, "Confirma a alteração", "Alteração", JOptionPane.YES_NO_OPTION);

                    if (check == 0) {

                        listaC.alterarListaMusica();
                        nomeLista.setText(""); // Limpar input
                        readTableLista();

                    }
                } else {
                    this.messageJOptionPane("Você não alterou o nome da lista");
                }

            } else {
                this.messageJOptionPane(listaC.getRetornoMsg());
            }

        } else {
            this.messageJOptionPane("Selecione uma lista para alterar");
        }
    }//GEN-LAST:event_buttonAlterarPlayListaActionPerformed

    private void buttonCriarPlayListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCriarPlayListaActionPerformed

        PlayListaController listaC = new PlayListaController();

        listaC.setNome(nomeLista.getText());

        listaC.validInput();

        if (listaC.isValid()) {

            if (!veficarNomeIguaisLista()) { // Se nomes forem iguais não alterar o nome

                listaC.cadPlayLista();
                nomeLista.setText(""); // Limpar input
                readTableLista();
            } else {
                this.messageJOptionPane("Nome de lista já existe");
            }

        } else {
            this.messageJOptionPane(listaC.getRetornoMsg());
        }

    }//GEN-LAST:event_buttonCriarPlayListaActionPerformed

    private void buttonAddMusicaPlayListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddMusicaPlayListaActionPerformed
        if (jTListaM.getSelectedRow() != -1) {
            if (jTMusicas.getSelectedRow() != -1) {
                PlayListaController listaC = new PlayListaController();

                int idListaMusica = this.objListaM.get(jTListaM.getSelectedRow()).getIdLista();
                int idMusica = this.objMusica.get(jTMusicas.getSelectedRow()).getIdMusica();

                listaC.setLista_id(idListaMusica);
                listaC.setMusica_id(idMusica);

                listaC.adicionarMusicaNaLista();

            } else {
                this.messageJOptionPane("Selecione um música");
            }

        } else {
            this.messageJOptionPane("Selecione um lista");
        }

    }//GEN-LAST:event_buttonAddMusicaPlayListaActionPerformed

    private void searchMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMusicaActionPerformed

    private void buttonBuscarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarMusicaActionPerformed
        this.searchTableMusica(searchMusica.getText());
    }//GEN-LAST:event_buttonBuscarMusicaActionPerformed

    private void jTMusicasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTMusicasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMusicasKeyPressed

    private void jTMusicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMusicasMouseClicked

    }//GEN-LAST:event_jTMusicasMouseClicked

    public boolean veficarNomeIguaisLista() { // Se nomes forem iguais não alterar o nome

        boolean check = false;

        for (ObjetoListaMusica lm : this.objListaM) {

            if (nomeLista.getText().equals(lm.getNome())) {
                check = true;
            }

        }

        return check;
    }

    public void messageJOptionPane(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddMusicaPlayLista;
    private javax.swing.JButton buttonAlterarPlayLista;
    private javax.swing.JButton buttonBucarPlayLista;
    private javax.swing.JButton buttonBuscarMusica;
    private javax.swing.JButton buttonCriarPlayLista;
    private javax.swing.JButton buttonExcluirPlayLista;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTListaM;
    private javax.swing.JTable jTMusicas;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField nomeLista;
    private javax.swing.JTextField searchMusica;
    private javax.swing.JTextField searchPlayLista;
    // End of variables declaration//GEN-END:variables
}
