/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.locutor;

import controller.locutor.MusicaController;
import controller.locutor.PlayListaController;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import objetos.ObjetoEstiloMusical;
import objetos.ObjetoListaMusica;
import objetos.ObjetoMusica;
import sessao.Sessao;

/**
 *
 * @author leonardo
 */
public class TelaMusica extends javax.swing.JInternalFrame {

    private File fileMusica; // Musica a ser enviada
    private List<ObjetoMusica> objMusica;

    /**
     * Creates new form TelaEvento1
     */
    public TelaMusica() {
        initComponents();
        listarEstiloMusicais();
        readTableMusica();
    }

    public void readTableMusica() {
        DefaultTableModel modelo = (DefaultTableModel) jTMusicas.getModel();

        modelo.setNumRows(0); // Limpando a tabela

        MusicaController musicaC = new MusicaController();

        this.objMusica = musicaC.listarListasMusicas();

        for (ObjetoMusica m : this.objMusica) {

            modelo.addRow(new Object[]{
                m.getNome(),
                m.getNomeCantor()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeMusica = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nomeAlbum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nomeCantor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nomeBanda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        estiloMusical = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        buttonBuscarFile = new javax.swing.JButton();
        nomeFile = new javax.swing.JLabel();
        buttonAddMusica = new javax.swing.JButton();
        buttonAlterarMusica = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTMusicas = new javax.swing.JTable();

        jLabel3.setText("jLabel3");

        jTextField3.setText("jTextField3");

        jMenu1.setText("jMenu1");

        setClosable(true);
        setIconifiable(true);
        setTitle("Adicionar Música");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Música"));

        jInternalFrame1.setClosable(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setText("Nome Música:");

        jLabel7.setText("Álbum:");

        jLabel8.setText("Nome Cantor:");

        jLabel10.setText("Banda:");

        jLabel12.setText("Estilo Musical:");

        estiloMusical.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(nomeCantor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(nomeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(67, 67, 67)
                            .addComponent(nomeBanda, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nomeAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(estiloMusical, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 250, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 251, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCantor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nomeBanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(nomeAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(estiloMusical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 87, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 86, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 134, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("File Música"));

        jInternalFrame2.setClosable(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("File Música:");

        buttonBuscarFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        buttonBuscarFile.setText("Buscar ");
        buttonBuscarFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonBuscarFile)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeFile, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 250, Short.MAX_VALUE)
                    .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 251, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBuscarFile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 44, Short.MAX_VALUE)
                    .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 43, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 12, -1, -1));

        buttonAddMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        buttonAddMusica.setText("Adicionar Música");
        buttonAddMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddMusicaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAddMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 354, -1, -1));

        buttonAlterarMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        buttonAlterarMusica.setText("Alterar Música");
        buttonAlterarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarMusicaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAlterarMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 354, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Músicas"));

        jTMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cantor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTMusicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMusicasMouseClicked(evt);
            }
        });
        jTMusicas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTMusicasKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(jTMusicas);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 12, -1, -1));

        setBounds(250, 20, 964, 424);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddMusicaActionPerformed
        // TODO add your handling code here:

        MusicaController musicaC = new MusicaController();

        musicaC.setNome(nomeMusica.getText());
        musicaC.setBanda(nomeBanda.getText());
        musicaC.setNomeCantor(nomeCantor.getText());
        musicaC.setAlbum(nomeAlbum.getText());
        musicaC.setEstiloMusical(estiloMusical.getSelectedItem().toString());
        musicaC.setNomeFileMusica(nomeFile.getText());

        musicaC.setFileMusica(this.fileMusica);

        musicaC.validInputs();

        if (musicaC.isValid()) {

            musicaC.enviarMusicaPasta();

            if (musicaC.isValid()) { // Envia a música

                musicaC.cadMusica(); // cadastra a música 
                //Limpar Inputs
                nomeMusica.setText("");
                nomeBanda.setText("");
                nomeCantor.setText("");
                nomeAlbum.setText("");
                estiloMusical.setSelectedItem("Selecione");
                nomeFile.setText("");
                readTableMusica();

            } else {
                this.messageJOptionPane(musicaC.getRetornoMsg());
            }
        } else {
            this.messageJOptionPane(musicaC.getRetornoMsg());
        }

    }//GEN-LAST:event_buttonAddMusicaActionPerformed

    private void buttonBuscarFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarFileActionPerformed

        JFileChooser filechooser = new JFileChooser();
        filechooser.setDialogTitle("Procurar Múscia");
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        long tamnhoPermitido = 15000000; // 15 Megabyte

        FileNameExtensionFilter filter = new FileNameExtensionFilter("MP3 Música ", "mp3");

        filechooser.setFileFilter(filter);
        filechooser.showOpenDialog(this);

        int retorno = filechooser.showOpenDialog(this);

        if (retorno == JFileChooser.APPROVE_OPTION) {

            if (filechooser.getSelectedFile().length() < tamnhoPermitido) {
                this.fileMusica = filechooser.getSelectedFile();
                nomeFile.setText(fileMusica.getName()); // Show o nome do file 
            } else {
                this.messageJOptionPane("Arquivo muito grande, é permitido até 15 Megabyte");
            }

        }


    }//GEN-LAST:event_buttonBuscarFileActionPerformed

    private void buttonAlterarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarMusicaActionPerformed
        if (jTMusicas.getSelectedRow() != -1) {
            ObjetoMusica dadosMusica = this.objMusica.get(jTMusicas.getSelectedRow());
            
            MusicaController musicaC = new MusicaController();

            musicaC.setNome(nomeMusica.getText());
            musicaC.setBanda(nomeBanda.getText());
            musicaC.setNomeCantor(nomeCantor.getText());
            musicaC.setAlbum(nomeAlbum.getText());
            musicaC.setEstiloMusical(estiloMusical.getSelectedItem().toString());
            musicaC.setNomeFileMusica("file");
            musicaC.setId_musica(dadosMusica.getIdMusica());

            musicaC.validInputs();

            if (musicaC.isValid()) {
                if (verifAlteracaoMusica()) {
                    int check = JOptionPane.showConfirmDialog(null, "Confirma a alteração", "Alteração", JOptionPane.YES_NO_OPTION);

                    if (check == 0) {

                        musicaC.alterarMusica();

                        readTableMusica();

                    }
                } else {
                    this.messageJOptionPane("Você não alterou dados da música");
                }

            } else {
                this.messageJOptionPane(musicaC.getRetornoMsg());
            }

        } else {
            this.messageJOptionPane("Selecione uma música para alterar");
        }
    }//GEN-LAST:event_buttonAlterarMusicaActionPerformed

    private boolean verifAlteracaoMusica() {
        boolean check = true;

        ObjetoMusica dadosMusica = this.objMusica.get(jTMusicas.getSelectedRow());
        

        if (nomeMusica.getText().equals(dadosMusica.getNome()) && nomeCantor.getText().equals(dadosMusica.getNomeCantor()) && nomeBanda.getText().equals(dadosMusica.getBanda()) && nomeAlbum.getText().equals(dadosMusica.getAlbum()) && estiloMusical.getSelectedItem().toString().equals(dadosMusica.getEstiloMusical())) {
            check = false;
        } 

        return check;
    }

    private void jTMusicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMusicasMouseClicked
        ObjetoMusica musica = this.objMusica.get(jTMusicas.getSelectedRow()); // Música do Play

        nomeMusica.setText(musica.getNome());
        nomeBanda.setText(musica.getBanda());
        nomeCantor.setText(musica.getNomeCantor());
        nomeAlbum.setText(musica.getAlbum());
        estiloMusical.setSelectedItem(musica.getEstiloMusical());
    }//GEN-LAST:event_jTMusicasMouseClicked

    private void jTMusicasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTMusicasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMusicasKeyPressed

    private void listarEstiloMusicais() {
        for (ObjetoEstiloMusical EM : Sessao.getDadosEstiloM()) {
            estiloMusical.addItem(EM.getNome());
        }
    }

    private void messageJOptionPane(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddMusica;
    private javax.swing.JButton buttonAlterarMusica;
    private javax.swing.JButton buttonBuscarFile;
    private javax.swing.JComboBox<String> estiloMusical;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTMusicas;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField nomeAlbum;
    private javax.swing.JTextField nomeBanda;
    private javax.swing.JTextField nomeCantor;
    private javax.swing.JLabel nomeFile;
    private javax.swing.JTextField nomeMusica;
    // End of variables declaration//GEN-END:variables
}
