/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.radio;

import java.util.List;
import objetos.ObjetoRadio;

/**
 *
 * @author leonardo
 */
public class TelaRadio extends javax.swing.JInternalFrame {

    private List<ObjetoRadio> objRadio;

    /**
     * Creates new form TelaEvento1
     */
    public TelaRadio() {
        initComponents();
        readTable();
    }

    public void readTable() {
//        DefaultTableModel modelo = (DefaultTableModel) jTEventos.getModel();
//
//        modelo.setNumRows(0); // Limpando a tabela
//
//        Radio radio = new Radio();
//
//        this.objRadio = radio.listasRadios();
//
//        for (ObjetoRadio rd : this.objRadio) {
//            
//            String status = rd.getRadioBloqueada() == true ? "Bloqueado" : "OK";
//
//            modelo.addRow(new Object[]{
//                rd.getId(),
//                rd.getNome(),
//                rd.getCnpj(),
//                status
//            });
//
//        }

    }

    public void readTableForSearch(String search) {
//        DefaultTableModel modelo = (DefaultTableModel) jTEventos.getModel();
//        
//
//        modelo.setNumRows(0); // Limpando a tabela
//
//        Radio radio = new Radio();
//
//        this.objRadio = radio.searchRadio(search);
//
//        for (ObjetoRadio rd : this.objRadio) { // Pesquisando no banco usando LIKE, Se existe algo no mesmo
//            
//            String status = rd.getRadioBloqueada() == true ? "Bloqueado" : "OK";
//            
//            modelo.addRow(new Object[]{ // Adicionando dados na tabela
//                rd.getId(),
//                rd.getNome(),
//                rd.getCnpj(),
//                status
//            });
//
//        }
        

    }

//    private JComponent CoresTable(DefaultTableModel defaulTableModel) {
//        JTable jTable = new JTable(defaulTableModel) {
//
//            @Override
//            public Component prepareRenderer(TableCellRenderer renderer, int row, int colunm ) {
//                Component component = super.prepareRenderer(renderer, row, colunm);
//                
//                int linha = convertRowIndexToModel(row);
//                
//                String status = (String) getModel().getValueAt(linha, 3);
//                
//                if("Bloqueado".equals(status) ){
//                    component.setBackground(Color.RED);
//                }
//                
//                return component;
//            }
//        };
//        
//        return new JScrollPane(jTable);
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jTextField3.setText("jTextField3");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Radios");
        setToolTipText("");

        jLabel11.setText("Em desenvolvimento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel11)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        setBounds(250, 20, 602, 550);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
